// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-uYeXwHJroYk_5tI2dLZ9jKTDP8WVFQ',
    appId: '1:1040369952210:web:6c1a2b1df607610993d40b',
    messagingSenderId: '1040369952210',
    projectId: 'bynry-assignment-907c8',
    authDomain: 'bynry-assignment-907c8.firebaseapp.com',
    storageBucket: 'bynry-assignment-907c8.appspot.com',
    measurementId: 'G-2ZQVW6JW8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJgb5BOrIB2YbfzJ9VPD-cQXfb8CWd7iA',
    appId: '1:1040369952210:android:31c149dff2c4f94f93d40b',
    messagingSenderId: '1040369952210',
    projectId: 'bynry-assignment-907c8',
    storageBucket: 'bynry-assignment-907c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMc4hO6SxGF7OUt-qKTgyFnrUFAPNojt4',
    appId: '1:1040369952210:ios:59ec82d9712cf75093d40b',
    messagingSenderId: '1040369952210',
    projectId: 'bynry-assignment-907c8',
    storageBucket: 'bynry-assignment-907c8.appspot.com',
    iosBundleId: 'com.example.bynryAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMc4hO6SxGF7OUt-qKTgyFnrUFAPNojt4',
    appId: '1:1040369952210:ios:e439622fc214203f93d40b',
    messagingSenderId: '1040369952210',
    projectId: 'bynry-assignment-907c8',
    storageBucket: 'bynry-assignment-907c8.appspot.com',
    iosBundleId: 'com.example.bynryAssignment.RunnerTests',
  );
}
